const a = (window.qmn_quiz_data['3'] = {
  quiz_id: '3',
  quiz_name: 'Hevit NEWW',
  disable_answer: '0',
  ajax_show_correct: '0',
  progress_bar: '0',
  contact_info_location: '0',
  qpages: {
    1: {id: '1', quizID: '2', pagekey: 'igmmOuLK', hide_prevbtn: '0'},
    2: {id: '2', quizID: '2', pagekey: '5sRek2az', hide_prevbtn: '0'},
    3: {id: '3', quizID: '2', pagekey: 'pwWAqWaH', hide_prevbtn: '0'},
    4: {id: '4', quizID: '2', pagekey: 'Oxhk20SL', hide_prevbtn: '0'},
    5: {id: '5', quizID: '2', pagekey: 'kzfWd3sK', hide_prevbtn: '0'},
    6: {id: '6', quizID: '2', pagekey: 'kz2iYqrJ', hide_prevbtn: '0'},
    7: {id: '7', quizID: '2', pagekey: 'YyhL9K0s', hide_prevbtn: '0'},
    8: {id: '8', quizID: '2', pagekey: '4emiSw7Y', hide_prevbtn: '0'},
    9: {id: '9', quizID: '2', pagekey: 'NmfTQPvZ', hide_prevbtn: '0'},
    10: {id: '10', quizID: '2', pagekey: 'RuPz29R2', hide_prevbtn: '0'},
    11: {id: '11', quizID: '2', pagekey: 'XW5DUOzo', hide_prevbtn: '0'},
  },
  skip_validation_time_expire: '0',
  timer_limit_val: 0,
  disable_scroll_next_previous_click: '0',
  disable_first_page: '0',
  enable_result_after_timer_end: '0',
  enable_quick_result_mc: '0',
  end_quiz_if_wrong: '0',
  form_disable_autofill: '0',
  disable_mathjax: '0',
  enable_quick_correct_answer_info: '0',
  quick_result_correct_answer_text:
    'Correct! You have selected correct answer.',
  quick_result_wrong_answer_text: 'Wrong! You have selected wrong answer.',
  quiz_processing_message: '',
  not_allow_after_expired_time: '',
  scheduled_time_end: false,
  pagination: {
    amount: 1,
    section_comments: '1',
    total_questions: 11,
    previous_text: 'PREVIOUS',
    next_text: 'NEXT',
    start_quiz_survey_text: 'ENTER',
  },
  error_messages: {
    email_error_text: 'Not a valid e-mail address!',
    number_error_text: 'This field must be a number!',
    incorrect_error_text: 'The entered text is not correct!',
    empty_error_text: 'Belum di isi nih!',
    url_error_text: 'The entered URL is not valid!',
    minlength_error_text: 'Required atleast %minlength% characters.',
    maxlength_error_text: 'Maximum %maxlength% characters allowed.',
  },
  question_list: {
    20: {
      question_id: '20',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:23:"a. Menjadi lebih berani";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:40:"b. Dapat melakukan hal menantang lainnya";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:34:"c. Siap untuk menghadapi perubahan";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:47:"d. Harus mengambil resiko untuk jadi lebih baik";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:49:"Ketika aku berani mengambil risiko, aku merasa\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menjadi lebih berani', 10, 0],
        ['b. Dapat melakukan hal menantang lainnya', 20, 0],
        ['c. Siap untuk menghadapi perubahan', 30, 0],
        ['d. Harus mengambil resiko untuk jadi lebih baik', 40, 0],
      ],
    },
    21: {
      question_id: '21',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:30:"a. Menerima dengan lapang dada";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:25:"b. Belajar dari kekalahan";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:36:"c. Cari kesempatan di kompetisi lain";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:17:"d. Apa itu kalah?";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:40:"Ketika menghadapi kekalahan, aku akan\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menerima dengan lapang dada', 10, 0],
        ['b. Belajar dari kekalahan', 20, 0],
        ['c. Cari kesempatan di kompetisi lain', 30, 0],
        ['d. Apa itu kalah?', 40, 0],
      ],
    },
    22: {
      question_id: '22',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:16:"a. Menonton film";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:41:"b. Merencanakan hal yang harus dikerjakan";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:45:"c. Mengerjakannya dengan penuh tanggung jawab";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:35:"d. Menyelesaikannya dalam satu hari";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:55:"Ketika aku harus mencicil sebuah pekerjaan, aku akan\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menonton film', 10, 0],
        ['b. Merencanakan hal yang harus dikerjakan', 20, 0],
        ['c. Mengerjakannya dengan penuh tanggung jawab', 30, 0],
        ['d. Menyelesaikannya dalam satu hari', 40, 0],
      ],
    },
    23: {
      question_id: '23',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:24:"a. Bermain game seharian";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:23:"b. Membuat sebuah karya";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:21:"c. Membersihkan kamar";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:59:"d. Membuat jadwal kegiatan esok dengan lengkap &amp; detail";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:45:"Apabila aku memiliki waktu luang, aku akan\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Bermain game seharian', 10, 0],
        ['b. Membuat sebuah karya', 20, 0],
        ['c. Membersihkan kamar', 30, 0],
        ['d. Membuat jadwal kegiatan esok dengan lengkap &amp; detail', 40, 0],
      ],
    },
    24: {
      question_id: '24',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:31:"a. Lemas dan sulit untuk bangun";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:37:"b. Mengantuk, namun tetap berolahraga";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:45:"c. Dapat mengawali hari dengan lebih semangat";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:37:"d. Tertantang untuk hidup lebih sehat";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:55:"Ketika aku bangun pagi untuk berolahraga, aku merasa\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Lemas dan sulit untuk bangun', 10, 0],
        ['b. Mengantuk, namun tetap berolahraga', 20, 0],
        ['c. Dapat mengawali hari dengan lebih semangat', 30, 0],
        ['d. Tertantang untuk hidup lebih sehat', 40, 0],
      ],
    },
    25: {
      question_id: '25',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:49:"a. Menghasilkan sesuatu yang bagus dan bermanfaat";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:52:"b. Mendapat kesempatan untuk mencari minat dan bakat";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:27:"c. Mencari pengetahuan baru";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:59:"d. Mengasah kemampuan baru sambil memanfaatkan potensi diri";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:72:"Aku gemar mengeksplorasi hal baru di waktu senggang, karena aku ingin\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menghasilkan sesuatu yang bagus dan bermanfaat', 10, 0],
        ['b. Mendapat kesempatan untuk mencari minat dan bakat', 20, 0],
        ['c. Mencari pengetahuan baru', 30, 0],
        ['d. Mengasah kemampuan baru sambil memanfaatkan potensi diri', 40, 0],
      ],
    },
    26: {
      question_id: '26',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:35:"a. Mencapai tujuan yang lebih besar";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:34:"b. Mengeksplorasi kemungkinan baru";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:55:"c. Mencegah kesulitan yang akan dialami dikemudian hari";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:38:"d. Meningkatkan keahlian yang dimiliki";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:70:"Aku selalu melatih kembali keahlian yang dimiliki, karena aku ingin\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Mencapai tujuan yang lebih besar', 10, 0],
        ['b. Mengeksplorasi kemungkinan baru', 20, 0],
        ['c. Mencegah kesulitan yang akan dialami dikemudian hari', 30, 0],
        ['d. Meningkatkan keahlian yang dimiliki', 40, 0],
      ],
    },
    27: {
      question_id: '27',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:27:"a. Mempersiapkan banyak hal";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:32:"b. Melatih kemampuan bangun pagi";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:24:"c. Menghindari kemacetan";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:26:"d. Membiasakan bangun pagi";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:75:"Aku selalu bangun lebih pagi sebelum memulai aktivitas, karena aku ingin\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Mempersiapkan banyak hal', 10, 0],
        ['b. Melatih kemampuan bangun pagi', 20, 0],
        ['c. Menghindari kemacetan', 30, 0],
        ['d. Membiasakan bangun pagi', 40, 0],
      ],
    },
    29: {
      question_id: '29',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:26:"a. Menambah kemampuan baru";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:44:"b. Mencari kemampuan terpendam di dalam diri";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:27:"c. Mendalami kemampuan baru";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:30:"d. Memanfaatkan kemampuan baru";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:54:"Aku senang mengikuti kelas online, karena aku ingin\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menambah kemampuan baru', 10, 0],
        ['b. Mencari kemampuan terpendam di dalam diri', 20, 0],
        ['c. Mendalami kemampuan baru', 30, 0],
        ['d. Memanfaatkan kemampuan baru', 40, 0],
      ],
    },
    28: {
      question_id: '28',
      quiz_id: '3',
      question_name: '',
      answer_array:
        'a:4:{i:0;a:3:{i:0;s:38:"a. Menyelesaikan pekerjaan lebih cepat";i:1;d:10;i:2;i:0;}i:1;a:3:{i:0;s:25:"b. Melatih sifat disiplin";i:1;d:20;i:2;i:0;}i:2;a:3:{i:0;s:39:"c. Mengantisipasi adanya tambahan kerja";i:1;d:30;i:2;i:0;}i:3;a:3:{i:0;s:38:"d. Menyelesaikan pekerjaan tepat waktu";i:1;d:40;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '0',
      question_settings:
        'a:14:{s:8:"required";i:0;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:59:"Aku melakukan pekerjaan dengan efisien, karena aku ingin\u2026";s:14:"featureImageID";s:0:"";s:15:"featureImageSrc";s:0:"";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [
        ['a. Menyelesaikan pekerjaan lebih cepat', 10, 0],
        ['b. Melatih sifat disiplin', 20, 0],
        ['c. Mengantisipasi adanya tambahan kerja', 30, 0],
        ['d. Menyelesaikan pekerjaan tepat waktu', 40, 0],
      ],
    },
    30: {
      question_id: '30',
      quiz_id: '3',
      question_name: '',
      answer_array: 'a:1:{i:0;a:3:{i:0;s:0:"";i:1;d:0;i:2;i:0;}}',
      answer_one: '',
      answer_one_points: '0',
      answer_two: '',
      answer_two_points: '0',
      answer_three: '',
      answer_three_points: '0',
      answer_four: '',
      answer_four_points: '0',
      answer_five: '',
      answer_five_points: '0',
      answer_six: '',
      answer_six_points: '0',
      correct_answer: '0',
      question_answer_info: '',
      comments: '1',
      hints: '',
      question_order: '1',
      question_type: '0',
      question_type_new: '3',
      question_settings:
        'a:14:{s:8:"required";i:1;s:12:"answerEditor";s:4:"text";s:14:"question_title";s:3:"\u200e";s:14:"featureImageID";s:3:"309";s:15:"featureImageSrc";s:78:"https://test-havit.cubix.co.id/wp-content/uploads/2023/02/biar-makin-ambis.png";s:11:"matchAnswer";s:6:"random";s:14:"case_sensitive";s:0:"";s:16:"image_size-width";s:0:"";s:17:"image_size-height";s:0:"";s:8:"autofill";s:0:"";s:10:"limit_text";s:1:"0";s:23:"limit_multiple_response";s:1:"0";s:17:"file_upload_limit";s:1:"0";s:16:"file_upload_type";s:0:"";}',
      category: '',
      deleted: '0',
      deleted_question_bank: '0',
      answers: [['', 0, 0]],
    },
  },
  first_page: true,
});
